android.useAndroidX=true
android.enableJetifier=true
# android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
org.gradle.jvmargs=-Xmx4096m -Duser.language=en -Duser.country=US
# Work around intermittent Kotlin daemon connection issues on some local setups.
kotlin.compiler.execution.strategy=in-process
flutter.compileSdkVersion=35
flutter.targetSdkVersion=35