// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtc3HqQ0L47uQECIqDxyVUbOo178W4Ap0',
    appId: '1:594263645890:web:864b63a32405288601a55b',
    messagingSenderId: '594263645890',
    projectId: 'balsam-academy',
    authDomain: 'balsam-academy.firebaseapp.com',
    storageBucket: 'balsam-academy.firebasestorage.app',
    measurementId: 'G-2YPY9SBF7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlB7qjqK6wcpE8TJclvXCLzxAiKNiJ9FM',
    appId: '1:594263645890:android:9c581002b3cab7c101a55b',
    messagingSenderId: '594263645890',
    projectId: 'balsam-academy',
    storageBucket: 'balsam-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6BFMfr9HgXxD0rhCc_GetcjLJ2crI90',
    appId: '1:594263645890:ios:93e25ec24b495f3a01a55b',
    messagingSenderId: '594263645890',
    projectId: 'balsam-academy',
    storageBucket: 'balsam-academy.firebasestorage.app',
    iosBundleId: 'com.balsamacademy.app',
  );
}
